### ISSUE TITLE
Epic-001-호나므로 기본 레이아웃 및 메인 페이지 작성

### ISSUE THREAD

**Issue by bonomoon** [2021-oasis-hackathon/berserkers#1]
### Overview
- Stakeholders: 사용자, 개발자

- We want to: 
  - 서비스 처음 접속 시 메인 페이지가 나와야 함
  - 서비스 소개를 알고 싶음
  - 서비스에서 무엇을 제공하는지 파악하고 싶음
  - 서비스의 균일한 템플릿을 메인 페이지부터 맞추고 싶음(개발자)
- So that:
  - 이 서비스를 처음보는 사람들이 보고 어떤 서비스인지 정체성을 파악할 수 있도록
  - 서비스에 관심을 가지게 되고 세부 콘텐츠까지 탐색할 수 있게 하기 위해

### Acceptable Criteria
- [x] 필요한 페이지들에 대해 템플레이팅이 되어 있는가? (나중에 새로 만들 일이 없는가?)
- [x] 서비스 도메인 index에 접근 시 메인 페이지로 접속되는가?
- [x] 템플릿에 들어갈 내용과 디자인된 프로토타입이 일치하는가?
- [x] 기획한 기능들에 대한 간략한 설명 또는 콘텐츠 프리뷰가 들어가 있는가?

### Tasks
- [x] Vue-Router를 사용하여 페이지별로 로딩될 수 있는 Router 제작
- [x] Vuetify를 이용하여 템플릿 제작
- [x] 템플릿에 들어갈 내용은 디자인된 프로토타입을 확인하고 넣을 것
- [x] 서비스 소개: 디자인된 내용에 따라서 순서 맞춰서 제작
- [x] 개인 모임을 탐색할 수 있는 추천 콘텐츠 리스트 제작
- [x] 지역 공동체 프로그램을 탐색할 수 있는 추천 콘텐츠 리스트 제작

### Resource
1. 서비스 소개
  - 호나므로란?
  - 프로그램을 만들수도있어요! - 개인은 모임을 만들고 공동체는 저희와 협약 또는 기획한 프로그램을 등록할 수 있습니다.
  - 호남 지도를 통해 현재 어디서 어떤 프로그램들이 등록되어 있는지 확인(선택)
