### ISSUE TITLE
E001-Main Header 구성

### ISSUE THREAD

**Issue by bonomoon** [2021-oasis-hackathon/berserkers#5]
> [Epic 001 호나므로 기본 레이아웃 및 메인 페이지 작성](1)

### Overview
- Stakeholders: 사용자

- We want to: 
  - 서비스를 메뉴를 통해 파악하고 탐색 가능하고 싶음
 
- So that:
  - 카테고리별로 정확한 정보를 탐색할 수 있도록

### Acceptable Criteria
- [x] Main Header: 로고 / 개인 프로그램, 지역 공동체 프로그램, 프로그램 관리 / 사용자 정보
- [x] 각각 URL Domain Mapping이 제대로 되어 있는가? 
  - [x] 개인 프로그램: /personal-program
  - [x] 지역 공동체 프로그램: /local-community-program
  - [x] 프로그램 관리: /program-management

### Tasks
- [x] Vue-Router를 사용하여 페이지별로 로딩될 수 있는 Router 제작
- [x] Vuetify를 이용하여 헤더 템플릿 제작(로고, 링크 콘텐츠, 사용자 프로필 미리보기)
- [x] 템플릿에 들어갈 내용은 디자인된 프로토타입을 확인하고 넣을 것
