### ISSUE TITLE
E001-기본 레이아웃 생성

### ISSUE THREAD

**Issue by bonomoon** [2021-oasis-hackathon/berserkers#6]
> [Epic 001 호나므로 기본 레이아웃 및 메인 페이지 작성](1)

### Overview
- Stakeholders: 개발자

- We want to: 
  - 서비스 개발하면서 기본 레이아웃을 잡고 재사용하고 싶음
- So that:
  - 개발 생산성 향상 및 균일한 디자인 적용

### Acceptable Criteria
- [x] 디자인된 프로토타입과 레이아웃 구성이 일치하는가?
- [x] Header, Footer, Content Container Layout
- [x] Introduction Page Layout
- [x] Content Page Layout: 개인 프로그램, 지역 공동체 프로그램 콘텐츠 리스트 페이지
  - [x] Content Detail Page Layout: 프로그램들의 세부 소개 및 설명 / Q&A 댓글
- [ ] My Page Layout: 프로그램 관리

### Tasks
- [x] Vuetify를 이용하여 템플릿 제작
- [x] 템플릿에 들어갈 내용은 디자인된 프로토타입을 확인하고 넣을 것
