### ISSUE TITLE
E001-메인 콘텐츠 미리보기 컴포넌트 제작

### ISSUE THREAD

**Issue by bonomoon** [2021-oasis-hackathon/berserkers#7]
> [Epic 001 호나므로 기본 레이아웃 및 메인 페이지 작성](1)

### Overview
- Stakeholders: 사용자, 개발자

- We want to: 
  - 콘텐츠의 미리보기 아이템들을 보고(ex. 쇼핑몰 아이템들) 이 프로그램들이나 모임이 어떤 것을 하는 것인지 알고 싶음
  - 콘텐츠 재사용으로 여러 페이지에서 그대로 사용할 수 있음
- So that:
  - 콘텐츠 탐색 시 관심을 가지거나 정보를 간략하게 얻을 수 있도록
  - 개발 생산성 향상

### Acceptable Criteria
- [x] 개인 프로그램 미리보기 아이템(추천에 들어감)
- [x] 지역 공동체 프로그램 미리보기 아이템(추천에 들어감)

### Tasks
- [x] Vuetify를 이용하여 컴포넌트 템플릿 제작
- [x] 템플릿에 들어갈 내용은 디자인된 프로토타입을 확인하고 넣을 것
- [x] 서비스 소개: 디자인된 내용에 따라서 순서 맞춰서 제작
- [x] 개인 프로그램 미리보기 아이템: 사진 / 이름 / 신청기간 / 일정 / 키워드 / 모집인원
- [x] 지역 공동체 프로그램 미리보기 아이템: 사진 / 위치 / 이름 / 신청기간 / 자가부담금 / 일정 / 키워드 / 참여인원

### Resource
1. 개인 프로그램 미리보기 아이템 예시

2. 지역 공동체 프로그램 미리보기 아이템 예시
